[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
cmd = 'cd server && npm ci'

[phases.build]
cmd = 'cd server && npm install typescript && npx tsc'

[start]
cmd = 'cd server && node dist/app.js'