[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
cmd = 'cd server && npm ci --include=dev && npm install typescript --save'

[phases.build]
cmd = 'cd server && node ./node_modules/typescript/bin/tsc'

[start]
cmd = 'cd server && node dist/app.js'