[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
cmd = 'cd server && npm install --include=dev'

[phases.build]
cmd = 'cd server && node ./node_modules/typescript/bin/tsc'

[start]
cmd = 'cd server && node dist/app.js'